// ─── Mission definitions ───────────────────────────────────────────────────
// All mission data lives here. Add new missions to this array.

export const MISSIONS = [
  {
    id:          'push-notifications',
    title:       'Turn On Notifications',
    description: 'Be the first to know when Algee drops. Enable push notifications and get hit the second something goes live.',
    points:      75,
    icon:        '🔔',
    color:       '#c4222e',
    category:    'Fan Perks',
    type:        'push',   // inline browser permission flow (no separate page)
  },
  {
    id:          'birthday',
    title:       'Tell Us Your Birthday',
    description: 'Share your birthday and get a special shoutout on your day.',
    points:      25,
    icon:        '🎂',
    color:       '#e8a020',
    category:    'Profile',
  },
  {
    id:          'fan-profile',
    title:       'Tell Us About You',
    description: 'Fill out your fan profile and let Algee know who you are.',
    points:      50,
    icon:        '◎',
    color:       '#c4222e',
    category:    'Profile',
    questions: [
      { id: 'city',        label: 'What city are you repping?',             type: 'text',   placeholder: 'e.g. Atlanta, GA'         },
      { id: 'fav_food',    label: 'Favorite food?',                         type: 'text',   placeholder: 'e.g. Jerk chicken'        },
      { id: 'fav_restaurant', label: 'Favorite restaurant?',               type: 'text',   placeholder: 'e.g. Dave\'s Hot Chicken' },
      { id: 'fav_icecream', label: 'Favorite ice cream flavor?',            type: 'text',   placeholder: 'e.g. Cookies & cream'     },
      { id: 'fav_song',    label: 'Favorite Algee song?',                   type: 'text',   placeholder: 'e.g. Love Lost'           },
      { id: 'fav_project', label: 'Favorite Algee film or show?',           type: 'text',   placeholder: 'e.g. The Hate U Give'     },
      { id: 'discovered',  label: 'How did you first discover Algee?',      type: 'textarea', placeholder: 'Tell the story...'       },
    ],
  },
  {
    id:          'follow-spotify',
    title:       'Follow on Spotify',
    description: 'Follow Algee on Spotify so you never miss a new drop. Stream Love Lost and everything that comes next.',
    points:      30,
    icon:        '🎵',
    color:       '#1db954',
    category:    'Music',
    type:        'external',
    url:         'https://open.spotify.com/artist/1r4hJ1h58CWwUQe3MxPuau',
  },
  {
    id:          'follow-instagram',
    title:       'Follow on Instagram',
    description: 'Follow @algeesmith on Instagram for behind-the-scenes, drops, and direct content.',
    points:      30,
    icon:        '📸',
    color:       '#e1306c',
    category:    'Social',
    type:        'external',
    url:         'https://www.instagram.com/algeesmith/',
  },
  {
    id:          'follow-youtube',
    title:       'Subscribe on YouTube',
    description: 'Subscribe to the official YouTube channel for music videos, freestyles, and exclusive footage.',
    points:      30,
    icon:        '▶',
    color:       '#ff0000',
    category:    'Music',
    type:        'external',
    url:         'https://www.youtube.com/@algeesmith',
  },
  {
    id:          'share-love-lost',
    title:       'Share Love Lost',
    description: 'Spread the word. Share the album with someone who needs to hear it.',
    points:      50,
    icon:        '🔗',
    color:       '#c4222e',
    category:    'Fan Perks',
    type:        'share',
    shareUrl:    'https://open.spotify.com/album/0Z2nmLYMKhilk7kstELKb9',
    shareText:   'Listen to Love Lost by Algee Smith 🎵',
  },
  {
    id:          'watch-video',
    title:       'Watch a Music Video',
    description: 'Hit play on the latest visual. Watch for 30 seconds, then mark it done.',
    points:      25,
    icon:        '🎬',
    color:       '#c4222e',
    category:    'Music',
    videoId:     'TjOHVPo5iwM',
  },
  {
    id:          'crossword',
    title:       'Algee Crossword Challenge',
    description: 'Seven clues. One puzzle. How well do you really know Algee? Fill in every answer to earn your points.',
    points:      50,
    icon:        '🟩',
    color:       '#c4882e',
    category:    'Fan Games',
    type:        'crossword',
  },
  {
    id:          'trivia-young-wild-free',
    title:       'Algee Trivia - Young Wild & Free',
    description: 'Test your knowledge. What 2 songs does Algee have in the movie Young Wild & Free?',
    points:      20,
    icon:        '🎬',
    color:       '#9b59b6',
    category:    'Film',
    type:        'trivia',
    question:    'What 2 songs does Algee have in the movie Young Wild & Free?',
    choices: [
      { id: 'a', label: 'Love Lost & Spiraling'  },
      { id: 'b', label: 'Safe & Sinners'          },
      { id: 'c', label: 'Better & Perfect'        },
      { id: 'd', label: 'Drip & Forever'          },
    ],
    correctId: 'b',
  },
]

// ─── Get a mission by id ──────────────────────────────────────────────────
export function getMission(id) {
  return MISSIONS.find(m => m.id === id) ?? null
}
